(()=>{'use strict';
const root=document.querySelector('#pure-plus-page'),reduce=matchMedia('(prefers-reduced-motion:reduce)').matches,phone=innerWidth<860,clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
if(!reduce&&!phone&&matchMedia('(pointer:fine)').matches&&window.Lenis){const lenis=new Lenis({duration:1.35,smoothWheel:true,syncTouch:false});requestAnimationFrame(function raf(t){lenis.raf(t);requestAnimationFrame(raf)})}
const sc=window.ScrollCraft?.mount(root);window.purePlusScroll=sc;const hero=root.querySelector('.hero');
if(window.gsap&&!reduce){const h=hero.querySelector('h1');h.setAttribute('aria-label',h.textContent);const walk=document.createTreeWalker(h,NodeFilter.SHOW_TEXT),nodes=[];while(walk.nextNode())nodes.push(walk.currentNode);nodes.forEach(t=>{const frag=document.createDocumentFragment();t.textContent.split(/(\s+)/).forEach(word=>{if(!word.trim()){frag.append(word);return}const w=document.createElement('span');w.className='hw';w.setAttribute('aria-hidden','true');[...word].forEach(c=>{const s=document.createElement('span');s.className='hch';s.textContent=c;w.append(s)});frag.append(w)});t.replaceWith(frag)});hero.classList.add('pp-animated');gsap.to(hero.querySelectorAll('.hch'),{opacity:1,y:0,duration:.55,ease:'power3.out',stagger:.018,delay:.5})}
const rmq=root.querySelector('#rmq'),reviewPause=root.querySelector('.sg-review-pause');let reviewPaused=false,reviewVisible=false;
if(!reduce){document.documentElement.classList.add('sg-review-motion');reviewPause.hidden=false;const lanes=[...rmq.querySelectorAll('.rrow')].map(row=>{const original=[...row.children];original.forEach(el=>{const c=el.cloneNode(true);c.inert=true;c.setAttribute('aria-hidden','true');row.append(c)});return {el:row,first:original[0],copy:row.children[original.length],dir:Number(row.dataset.dir),x:0,width:0}});function size(){lanes.forEach(l=>{l.width=l.copy.offsetLeft-l.first.offsetLeft;if(l.dir>0&&l.x===0)l.x=-l.width})}new ResizeObserver(size).observe(rmq);size();reviewPause.onclick=()=>{reviewPaused=!reviewPaused;reviewPause.textContent=reviewPaused?'Play reviews':'Pause reviews'};new IntersectionObserver(es=>reviewVisible=es[0].isIntersecting).observe(rmq);let last=performance.now(),lastY=scrollY,v=0;function reviews(t){const dt=Math.min((t-last)/1000,.05);last=t;const dy=scrollY-lastY;lastY=scrollY;v+=(phone?0:clamp(dy/Math.max(dt,.001)/900,-1,1)-v)*Math.min(1,dt*6);if(reviewVisible&&!reviewPaused&&!document.hidden)lanes.forEach(l=>{if(!l.width)return;l.x+=l.dir*(30+Math.abs(v)*260)*dt;if(l.x<=-l.width)l.x+=l.width;if(l.x>0)l.x-=l.width;l.el.style.transform=`translateX(${l.x}px) skewX(${-v*4}deg)`});requestAnimationFrame(reviews)}requestAnimationFrame(reviews);}
const q=root.querySelector('[data-qform]'),form=q.querySelector('form'),steps=[...form.querySelectorAll('[data-step]')],back=form.querySelector('[data-back]'),next=form.querySelector('[data-nextlabel]'),error=q.querySelector('.sh-error');let step=0,choice='';
function hidden(n,v){let x=form.querySelector(`[name="${n}"]`);if(!x){x=document.createElement('input');x.type='hidden';x.name=n;form.append(x)}x.value=v}
function choose(v){choice=v;hidden('system','Pure Flow');hidden('installation_preference',v);hidden('message',window.rvSummary?window.rvSummary(v):'Pure Flow installation request. Timing: '+v);form.querySelectorAll('.sysopt').forEach(x=>{const on=x.dataset.v===v;x.classList.toggle('on',on);x.setAttribute('aria-pressed',String(on))})}
function render(focus=true){steps.forEach((x,i)=>x.hidden=i!==step);back.hidden=!step;next.textContent=step===2?'Request my installation date':'Next';q.querySelectorAll('.steps i').forEach((x,i)=>x.classList.toggle('on',i<=step));error.hidden=true;if(focus)(steps[step].querySelector('input,button'))?.focus({preventScroll:true});sc?.layout()}
form.querySelectorAll('.sysopt').forEach(x=>x.onclick=()=>choose(x.dataset.v));back.onclick=()=>{step=Math.max(0,step-1);render()};
document.querySelectorAll('[data-system]').forEach(a=>a.addEventListener('click',()=>choose(a.dataset.system)));
form.addEventListener('submit',async e=>{e.preventDefault();error.hidden=true;for(const x of steps[step].querySelectorAll('input')){if(!x.checkValidity()){x.reportValidity();return}}if(step===1&&!choice){error.textContent='Please choose when you would like it installed.';error.hidden=false;return}if(step<2){step++;render();return}const submit=form.querySelector('[data-next]');submit.disabled=true;next.textContent='Sending…';try{hidden('_subject',(window.rvPackage?.()||'Pure Flow')+' installation request');hidden('system',window.rvPackage?.()||'Pure Flow');hidden('message',window.rvSummary?window.rvSummary(choice):'Pure Flow installation request');window.ffyStampForm?.(form);const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw Error('send');q.classList.add('sent');window.ffyLeadSuccess?.(form,{system:window.rvPackage?.()||'Pure Flow'});q.querySelector('.done').setAttribute('tabindex','-1');q.querySelector('.done').focus();}catch{error.textContent='Your enquiry could not be sent. Please try again or call 0430 546 749.';error.hidden=false;}finally{submit.disabled=false;next.textContent='Request my installation date';sc?.layout()}});0;render(false);


document.fonts.ready.then(()=>sc?.layout());addEventListener('load',()=>sc?.layout());})();