(()=>{'use strict';const root=document.querySelector('#pure-plus-page'),panel=root.querySelector('#reserve-colours');if(!panel)return;
const gallery=root.querySelector('.pp-gallery'),modes=[...root.querySelectorAll('[data-rc-mode]')],open=root.querySelector('.rc-open'),choice=root.querySelector('.rc-choice'),buttons=[...panel.querySelectorAll('.rc-swatch')],photo=panel.querySelector('#rc-image'),name=panel.querySelector('#rc-name'),status=panel.querySelector('.rc-status'),input=root.querySelector('[name=colour_preference]');let ticket=0;
root.querySelector('.rc-modes').hidden=false;open.hidden=false;choice.hidden=false;
function mode(colours){panel.hidden=!colours;gallery.hidden=colours;open.setAttribute('aria-expanded',String(colours));modes.forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.rcMode==='colours')===colours)));}
modes.forEach(b=>b.addEventListener('click',()=>mode(b.dataset.rcMode==='colours')));
open.addEventListener('click',()=>{mode(true);root.querySelector('.rc-gallery-wrap').scrollIntoView({block:'start',behavior:'instant'});buttons.find(b=>b.getAttribute('aria-pressed')==='true').focus({preventScroll:true});});
async function select(button){const token=++ticket;status.textContent='';panel.setAttribute('aria-busy','true');const image=new Image();image.src=button.dataset.src;
try{await image.decode();if(token!==ticket)return;photo.src=image.src;photo.alt='Pure Home Reserve in '+button.dataset.finish;panel.querySelector('.rc-photo').href=image.src;name.textContent=button.dataset.finish;choice.querySelector('strong').textContent=button.dataset.finish;input.value=button.dataset.finish;input.setAttribute('value',button.dataset.finish);panel.querySelector('.rc-count').textContent=String(buttons.indexOf(button)+1).padStart(2,'0')+' / 22';buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}
catch{if(token===ticket)status.textContent='That finish could not load. Please try again.';}finally{if(token===ticket)panel.removeAttribute('aria-busy');}}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>select(b));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight'||e.key==='ArrowDown')n=(i+1)%buttons.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')n=(i+buttons.length-1)%buttons.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=buttons.length-1;else return;e.preventDefault();buttons[n].focus();select(buttons[n]);});b.addEventListener('pointerenter',()=>{const img=new Image();img.src=b.dataset.src;},{once:true});});
})();
